### ISSUE TITLE
wysyłanie wiadomości do monitora

### ISSUE THREAD

**Issue by salberski** [DevelopersOrganizationFork/sensor#3]
Wiadomość przesyłana przez sensor do monitora powinna zawierać: nazwę (identyfikator) zasobu, nazwę metryki, dane pomiarowe (zależne od metryki).
Wiadomości powinny mieć formę tekstową. Sugerowany format bazowy: JSON.

Do tworzenia klas (DTO), które zostaną zmapowane na JSONa  można wykorzystać bibliotekę `com.fasterxml.jackson`

Przykład użycia:

```
@JsonInclude(JsonInclude.Include.NON_NULL)
public class SomeData {
    public String id;
    public String value;
}
```

**Comment by KamilSzelag** [comment]
Zadanie zamykam, stworzyłem już potrzebne klasy, być może wyjdzie, że jakieś klasy będzie trzeba dodać z informacjami. Jeśli będziemy jeszcze coś potrzebowali to stworzymy osobne issue.
