### ISSUE TITLE
integracja z monitorem

### ISSUE THREAD

**Issue by salberski** [DevelopersOrganizationFork/sensor#4]
Zastanowić się czy jest chęć/sens/czas na wymianę danych z monitorem z wykorzystaniem kolejki JMSowej, bądź innego, asynchronicznego, kolejkowego middleware'a. 

Jeśli nie, wykorzystać zwykły przesył pakietów protokołem UDP.

Zadbać o integrację z monitorem [!]

**Comment by marcinpilat** [comment]
Sensor może też wysyłać zapytania REST-owe. UDP może być zbyt niskopoziomowe. JMS może być bardzo ciekawy, ale nie wiem, czy ktoś od nas ma kompetencje w tym zakresie.

**Comment by KamilSzelag** [comment]
Ja teraz staram się to zrobić, zobaczymy co z tego wyjdzie.

**Comment by Silwest** [comment]
Chcemy osiagnac cos takiego gdzie jupiter to nasz monitor zgadza sie ?

http://docs.oracle.com/javaee/6/tutorial/doc/figures/jms-multiServer.gif

**Comment by KamilSzelag** [comment]
Tak wydaje mi się, że takie coś chcielibyśmy osiągnąć.
Sensory -> JMS <- monitor

**Comment by salberski** [comment]
Tak ma to wyglądać, zastanówcie się czy ten JMS da się w miarę ogarnąć. 
W monitorze dorobię moduł `monitor-sensor-integration` a tam jakiś pakiet `org.developers.monitor.sensor.consumer` coś w ten deseń.

@reynev REST odpada, tutaj powinno to działać asynchronicznie.

**Comment by Silwest** [comment]
Czyli mamy X komputerow z sensorem wysylajacych dane na jakis inny komputer na ktorym stoi JMS i Monitor odpytuje sobie tam kiedy chce ? Czy dobrze to rozumiem ?

**Comment by salberski** [comment]
Tak, dobrze rozumiesz, tak to powinno wyglądać.

**Comment by Silwest** [comment]
Czyli JMS to w zasadzie kolejny komponent tak jak Sensor right ?:>

**Comment by salberski** [comment]
No teoretycznie tak, ale wiem że te kolejki JMS są też implementowane po stronie serwera aplikacyjnego (Glassfish, JBoss, nie wiem czy w Tomcacie jest). Wtedy możnaby było się ograniczyć tylko do odpoweidniej konfiguracji tego.
Raczej to wymaga researchu, mogę też to z Wami poogarniać, bo sam jestem ciekawy, a na teraz nie jestem na 100% pewny jak to jest.

**Comment by Silwest** [comment]
Jezeli jest tak jak mowisz (ze to kwestia konfiguracji serwaera javay) to ja mysle ze JMS powinien byc po stronie monitora

**Comment by salberski** [comment]
Tak ;)

**Comment by KamilSzelag** [comment]
Zadanie zamykam, zrobiłemy wysyłanie do kolejki JMS. Po stronie Sensora dalszych prac nie przewiduję.

Użyłem AcitveMQ do JMS. Testowane na localhost oraz virtualnej maszynie. Na fatcat nie udało mi się tego połączenia zestawić. Trzeba będzie ustalić gdzie takie ActiveMQ będzie uruchomione, tzn komponent powinien się znajdować po stronie Monitora wiec stworzę issue w monitorze i opiszę co tam jeszcze będzie do zrobienia.
