### ISSUE TITLE
Run ActiveMQ in the Cloud

### ISSUE THREAD

**Issue by salberski** [DevelopersOrganizationFork/sensor#7]
Jak @KamilSzelag napisał:

> Użyłem AcitveMQ do JMS. Testowane na localhost oraz virtualnej maszynie. Na fatcat nie udało mi się tego połączenia zestawić. Trzeba będzie ustalić gdzie takie ActiveMQ będzie uruchomione, tzn komponent powinien się znajdować po stronie Monitora wiec stworzę issue w monitorze i opiszę co tam jeszcze będzie do zrobienia.

Można spróbować tego
https://blog.openshift.com/activemq-on-paas/

**Comment by KamilSzelag** [comment]
Czy issue nie powinno być w monitor-back ?

**Comment by salberski** [comment]
Ok. Przenoszę.
